### ISSUE TITLE
replace jshint + jscs by eslint

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-color-rgba-fallback#4]
example https://github.com/postcss/postcss-custom-properties/commit/78e550eb0e60c00f7430c70f5285872c2c8d1a40

Here is my current favorite eslint (when using es6)

```
---
# babel support more syntax stuff than eslint for now
parser: babel-eslint

ecmaFeatures:
  modules: true

env:
  es6: true
  browser: true
  node: true

# 0: off, 1: warning, 2: error
rules:
  # semicolons are useless
  semi: [2, "never"]

  quotes: [2, "double"]

  # 2 spaces indentation
  indent: [2, 2]

  # trailing coma are cool for diff
  comma-dangle: [2, "always-multiline"]

  # enforce comma at eol (never before)
  comma-style: [2, "last"]
  no-underscore-dangle: 0
```
